---
# Consul playbook on digital ocean
- name: Consul servers
  hosts: consul_servers
  become: true
  pre_tasks:
    - ansible.builtin.pause:
        minutes: 1
  roles:
    - role: ansible-role-consul-server
      internal_ip_range: 10.10.20.0/24
      do_region:
        slug: ams3
      